# AirGradient ONE - Board v9
# https://www.airgradient.com/open-airgradient/instructions/overview/

# Needs ESPHome 2023.7.0 or later

substitutions:
  devicename: "airgradient-one"
  upper_devicename: "AG One"
  ag_esphome_config_version: 0.2.2
  add_mac_suffix: "true"  # Must have quotes around value

# Enable Home Assistant API
api:

ota:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

packages:
  board: !include packages/airgradient_esp32-c3_board.yaml
  pm_2.5: !include packages/sensor_pms5003.yaml
  co2: !include packages/sensor_s8.yaml
  temp_humidity: !include packages/sensor_sht40.yaml
  tvoc: !include packages/sensor_sgp41.yaml
  # display: !include packages/display_sh1106_single_page.yaml
  display: !include packages/display_sh1106_multi_page.yaml
  led: !include packages/led.yaml
  led_co2: !include packages/led_co2.yaml
  airgradient_api: !include packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: !include packages/watchdog.yaml
  config_button: !include packages/config_button.yaml
  wifi: !include packages/sensor_wifi.yaml
  uptime: !include packages/sensor_uptime.yaml
  safe_mode: !include packages/switch_safe_mode.yaml

binary_sensor:
  - id: !extend config_button
    pin:
      ignore_strapping_warning: true  # Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
