---
# AirGradient Basic
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  devicename: "ag-basic"
  upper_devicename: "AG Basic"
  ag_esphome_config_version: 0.1.2
  add_mac_suffix: "true"  # Must have quotes around value

# Enable Home Assistant API
api:

ota:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

packages:
  board: !include packages/airgradient_d1_mini_board.yaml
  pm_2.5: !include packages/sensor_pms5003.yaml
  co2: !include packages/sensor_s8.yaml
  temp_humidity: !include packages/sensor_sht30.yaml
  display: !include packages/display_ssd1306.yaml
  airgradient_api: !include packages/airgradient_api_d1_mini_no_sgp41.yaml
  wifi: !include packages/sensor_wifi.yaml
  uptime: !include packages/sensor_uptime.yaml
  safe_mode: !include packages/switch_safe_mode.yaml
